// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiCUMD8sw6yDQkoi6sKw6lr5VIyvdR3nM',
    appId: '1:323535456672:web:0b0dd410fb52ed83ff7cc5',
    messagingSenderId: '323535456672',
    projectId: 'news-app-c678a',
    authDomain: 'news-app-c678a.firebaseapp.com',
    storageBucket: 'news-app-c678a.appspot.com',
    measurementId: 'G-FKHXCNXXMX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVOy-TWNlSW1K91g6Tazocg9vhDCKaZRg',
    appId: '1:323535456672:android:d07485f5cd04af55ff7cc5',
    messagingSenderId: '323535456672',
    projectId: 'news-app-c678a',
    storageBucket: 'news-app-c678a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVF5bhr_xPKadKPde1dhKbVxPSM71RVJE',
    appId: '1:323535456672:ios:8b36ea7cd49cf37dff7cc5',
    messagingSenderId: '323535456672',
    projectId: 'news-app-c678a',
    storageBucket: 'news-app-c678a.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );
}
